version: '3'
services:
  openapi-generator:
    image: openapitools/openapi-generator-cli
    command: generate -i /local/openapi.yml -g go-gin-server -o /project --additional-properties=packageName=domain,apiPath=domain
    volumes:
      - ./openapi:/local
      - .:/project
